name: Cornerstone Psychological Services
favicon: null
layout_spectrum: 0.15494
typography_spectrum: 0.42934826551936567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
