name: Cornerstone Psychological Services
favicon: null
layout_spectrum: 0.36062
typography_spectrum: 0.42934826551936567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8bbf43'
    - '#1f1a17'
    - '#8a8685'
    - '#4d4948'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
